#
# /********************************************************************************
#  Copyright (c) 2025 Contributors to the Eclipse Foundation
#  Copyright (c) 2025 LKS Next
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/
#

server:
  port: ${APPLICATION_PORT:8080}

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: SSI DIM Wallet stub
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;MODE=PostgreSQL}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    jpa:
      database-platform: ${SPRING_DATASOURCE_JPA_DATABASE-PLATFORM:}
  jpa:
    properties:
      hibernates:
        cache:
          use_second_level_cache: false
          use_query_cache: false

springdoc:
  swagger-ui:
    enabled: ${ENABLE_SWAGGER_UI:true}
    disable-swagger-default-url: true
    path: /ui/swagger-ui
    show-common-extensions: true
    csrf:
      enabled: true
  api-docs:
    enabled: ${ENABLE_API_DOC:true}
    path: /docs/api-docs

management:
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true

health:
  livenessState:
    enabled: true
  readinessState:
    enabled: true

# log level
logging:
  level:
    org:
      eclipse:
        tractusx:
          wallet:
            stub: ${APP_LOG_LEVEL:DEBUG}
stub:
  env: ${STUB_ENV:local}
  seedWalletsBPN: ${SEED_WALLETS_BPN:BPNL00000003AZQP,BPNL00000003AYRE}
  baseWalletBPN: ${BASE_WALLET_BPN:BPNL000000000000} # Operator BPN
  didHost: ${DID_HOST:localhost}
  stubUrl: ${STUB_URL:https://localhost} #Stub application host
  statusListVcId: ${STATUS_LIST_VC_ID:8a6c7486-1e1f-4555-bdd2-1a178182651e}
  token:
    tokenExpiryTime: ${TOKEN_EXPIRY_TIME:5} #in minutes
  portal:
    portalWaitTime: ${PORTAL_WAIT_TIME:60} # in seconds
    portalHost: ${PORTAL_HOST:http://localhost} # Portal backend host
    clientId: ${PORTAL_CLIENT_ID:portal_client_id} #keycloak client id
    clientSecret: ${PORTAL_CLIENT_SECRET:portal_client_secret} #keycloak client secret
    realm: ${PORTAL_REALM:wallet_test} #keycloak realm
    authServerUrl: ${PORTAL_AUTH_SERVER_URL:http://localhost:28080}  #Keycloak host
